services:
- docker

language: ruby
cache: bundler
sudo: false
rvm:
- 2.7.0

bundler_args: "--without kitchen_vagrant"

script: bundle exec kitchen test ${INSTANCE} --destroy=always

env:
  global:
  - KITCHEN_YAML=.kitchen.yml
  matrix:
  - INSTANCE=chef-15-ubuntu-1804
  - INSTANCE=chef-15-ubuntu-1604
  - INSTANCE=chef-15-fedora-latest
  - INSTANCE=chef-15-fedora-29
  - INSTANCE=chef-15-fedora-28
  - INSTANCE=chef-15-debian-9
  - INSTANCE=chef-15-debian-8
  - INSTANCE=chef-15-debian-10
  - INSTANCE=chef-15-centos-7
  - INSTANCE=chef-15-amazonlinux-2
  - INSTANCE=chef-15-amazonlinux
  - INSTANCE=chef-14-ubuntu-1804
  - INSTANCE=chef-14-ubuntu-1604
  - INSTANCE=chef-14-fedora-latest
  - INSTANCE=chef-14-fedora-29
  - INSTANCE=chef-14-fedora-28
  - INSTANCE=chef-14-debian-9
  - INSTANCE=chef-14-debian-8
  - INSTANCE=chef-14-debian-10
  - INSTANCE=chef-14-centos-7
  - INSTANCE=chef-14-amazonlinux-2
  - INSTANCE=chef-14-amazonlinux
  - INSTANCE=chef-13-ubuntu-1804
  - INSTANCE=chef-13-ubuntu-1604
  - INSTANCE=chef-13-fedora-latest
  - INSTANCE=chef-13-fedora-29
  - INSTANCE=chef-13-fedora-28
  - INSTANCE=chef-13-debian-9
  - INSTANCE=chef-13-debian-8
  - INSTANCE=chef-13-debian-10
  - INSTANCE=chef-13-centos-7
  - INSTANCE=chef-13-amazonlinux-2
  - INSTANCE=chef-13-amazonlinux
jobs:
  include:
  - stage: lint
    script:
    - bundle exec cookstyle --version
    - bundle exec cookstyle
    - bundle exec foodcritic --version
    - bundle exec foodcritic --contex --epic-fail any .
    - bundle exec rspec -fd test/cookbooks/testrig/spec/chefspec.rb
  - stage: deploy
    if: tag =~ ^[0-9]+\.[0-9]+\.[0-9]+$
    script:
    - openssl aes-256-cbc -K $encrypted_e35c8607da72_key -iv $encrypted_e35c8607da72_iv -in .travis/client.pem.enc -out .travis/client.pem -d
    - bundle exec stove login --username dr_agon --key .travis/client.pem
    - bundle exec stove --no-git
